trialConcurrency: 1
maxExecDuration: 100h
maxTrialNum: 200
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
experimentWorkingDirectory: ./nni-experiments
tuner:
  builtinTunerName: TPE
trial:
  command: CUDA_VISIBLE_DEVICES=2 python nni_main.py --datasets VQAv2 --bs 32 --save_path checkpoint_VQAv2 --epochs 3 --device_id 0
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
  maxTrialNumPerGpu: 7
